server:
  port: 0

spring:
  application:
    name: delivery-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.example.deliveryservice: DEBUG