server:
  port: 8000

spring:
  application: 
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
        routes:
          - id: shop-service
            uri: lb://SHOP-SERVICE
            predicates:
              - Path=/shop-service/**
            filters:
              - RewritePath=/shop-service/(?<segment>.*), /$\{segment}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.example.catalogservice: DEBUG