server:
  port: 0

spring:
  application:
    name: shop-service
  datasource:
    url: jdbc:mysql://localhost:3306/tp-delivery?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: sa
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    datasource: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.example.shopservice: DEBUG